### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by tiptronic** [AdamCarballo/streamdeck-distribution-tool#1]
I think it's not a good idea to still ship these outdated versions of DistributionTool!

You can find current ones here:

https://developer.elgato.com/documentation/stream-deck/sdk/packaging/

**Comment by AdamCarballo** [comment]
> I think it's not a good idea to still ship these outdated versions of DistributionTool!
> 
> 
> 
> You can find current ones here:
> 
> 
> 
> https://developer.elgato.com/documentation/stream-deck/sdk/packaging/

Hey, thanks for the heads-up, I'll update them as soon as I can after Xmas 😄

**Comment by AdamCarballo** [comment]
Updated binaries (they seem to be `v1.7`, while the old ones where `v1.5`) are now available and released as part of `v1.0.1`
